### ISSUE TITLE
Animation Parameter Options

### ISSUE THREAD

**Issue by patrickburk1988** [kandashi/kandashis-fluid-canvas#2]
**Describe the solution you'd like**
This may not even be possible, but it would be really cool to have the ability to tweak certain animation parameters (e.g. via the module settings menu). For example: I have no reason to use an earthquake animation, but if I had the option to decrease the animation's duration and intensity, I could instead use it for a monster's footstep.

**Comment by kandashi** [comment]
This is possible, but sometime in the future

**Comment by kandashi** [comment]
Now possible to call directly through macros with variable parameters
