### ISSUE TITLE
Feature Request: API

### ISSUE THREAD

**Issue by napolitanod** [kandashi/kandashis-fluid-canvas#3]
Would be cool to have it so these effects can be called via api. Would love to open up the ability to integrate with this with my module.

Thanks for all you do!

- Dan

**Comment by kandashi** [comment]
The API is open, just not documented :D
The class is FluidCanvas, with the different animations played starting here: https://github.com/kandashi/kandashis-fluid-canvas/blob/039dd2802af0737a4c82d078d5a3edb8aae162cd/scripts/fluidCanvas.js#L182

**Comment by napolitanod** [comment]
Thank you for the response. I cannot seem to find fluidCanvas in the console.log. Would that class not be available due to esmodules without registering it to the api?

**Comment by kandashi** [comment]
Oooh yes, yes it would. Ill push an update to make that avalaible now

**Comment by kandashi** [comment]
Now accessible thorugh the console/macros. The API doc is also avaliable
