### ISSUE TITLE
BUG: Sepia, Negative, Blur, Fade, and Drugged doesn't work on one-click.

### ISSUE THREAD

**Issue by GambetTV** [kandashi/kandashis-fluid-canvas#4]
It's possible this is working as intended, but if so the UI makes it confusing. Only Earthquake, Heart Beat, and Spin work on a single click. The others require you to Shift Click, and then Launch to activate it. Simply clicking the button does nothing,

Also, if you activate it for one person, you cannot keep it active for them and activate it for someone else, even by Shift Clicking and playing around with the controls. Instead it will deactivate it for the player(s) it's currently active for, and you have to re-apply them.

**Comment by kandashi** [comment]
It is not intended no. And the second is a little awkward to sort, but Im going to be working on it
