### ISSUE TITLE
Fluid Canvas shake does not push to players

### ISSUE THREAD

**Issue by EarlOfEnums** [kandashi/kandashis-fluid-canvas#6]
Fluid Canvas shake does not push to players when triggered by a danger zone

setup danger zone with fluid canvas's shake
setup danger zone for scene, set danger to shake, set targeting to all tokens, set trigger to end combat round
start combat
end a combat round, screen shakes like it's suppose to
log in on separate browser as player 
in original browser (logged in as gm) end combat round, shakes like it's suppose to
switch to player, no shake.
get friend to log in as player on their own computer
end combat round, shake for you (gm), no shake for friend (player)

**Expected behavior**
shake for player

**Screenshots**

**Environment:**
 - OS: windows
 - Browser chrome and firefox
 - Foundry Version 0.8.9
 - Module Version: danger zone: 0.0.8, fluid canvas: 0.2.04
 - All Modules Disabled: yes

**Comment by kandashi** [comment]
This will be an issue for Danger Zone, as the API has changed slightly in recent updates to make things more reliable

**Comment by kandashi** [comment]
I have updated the API documentation to reflect the new changes
