### ISSUE TITLE
Module doesn't seem to support v9

### ISSUE THREAD

**Issue by galaara98** [kandashi/kandashis-fluid-canvas#8]
**Describe the bug**

**To Reproduce**
1. upgrade core system to v9
2. scenes are all black, right click on scenes doesn't produce a menu

**Expected behavior**
Scenes are not broken :P

**Screenshots**

**Environment:**
 - OS: Ubuntu server/Windows client
 - Browser Edge Chromium 96
 - Foundry Version 9.238
 - Module Version 0.2.04
 - All Modules Disabled: Yes
 - Module List if no: 

**Additional context**

**Comment by kandashi** [comment]
that is correct

**Comment by galaara98** [comment]
Thanks for your hard work!
